### PR TITLE
Cod 54 need help

### PR DESCRIPTION
**Pull request by iTrip23**

### CODE REVIEW

**Comment by artcodespace** [comment]
What do you need help on Johnny? You can review your own stuff and comment on it to draw our attention to things

**Comment by iTrip23** [comment]
> What do you need help on Johnny? You can review your own stuff and comment on it to draw our attention to things

I need help with admin authetication

**Comment by artcodespace** [comment]
Ok first things first we need whatever is causing the deployment failure to be fixed - have a look at vercel by clicking on the details button and using the coding ducks gmail login (if you haven't done this before), it'll tell you what to look for.

**Comment by akbasmustafa** [comment]
All great

**Review by akbasmustafa — APPROVED** [review]
all works well

**Pull request merged**
